title: "Multilingual Documentation"
description: "A minimal example of multilingual just-the-docs"
baseurl: "/multilingual-doc-test"
url: "https://zachary62.github.io"

# Theme settings
remote_theme: just-the-docs/just-the-docs
color_scheme: light

# Enable plugins
plugins:
  - jekyll-remote-theme

# Enable search
search_enabled: true

# Default aux links
aux_links:
  "Source on GitHub":
    - "//github.com/zachary62/multilingual-doc-test"

# Set default language
defaults:
  -
    scope:
      path: ""
    values:
      lang: "en"
  -
    scope:
      path: "en/**"
    values:
      lang: "en"
  -
    scope:
      path: "zh/**"
    values:
      lang: "zh"

# Collections for each language
collections:
  en:
    output: true
    permalink: /:collection/:path/
  zh: 
    output: true
    permalink: /:collection/:path/

# Language names for UI
languages:
  en: English
  zh: 中文

# Just the Docs config (REMOVED)
# just_the_docs:
#   collections:
#     en:
#       name: English
#     zh:
#       name: 中文 